### ISSUE TITLE
Improve README 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#683] opened 2020-08-31 11:03 UTC
Current README can be improved in many ways:

1) add links to Ergo
2) Update "Getting started"
3) Provide links for documents inside repo (and not only)
4) Brief description of ErgoTree and ErgoScript
5) Add info on how to run the tests.
6) Add info on how to contribute.

**Comment by aslesarenko** [comment] 2020-09-10 13:00
Duplicate of #658

**Closed by aslesarenko** 2020-09-10 13:00 UTC
Labels: A-docs, C-enhancement, P2-medium
