### ISSUE TITLE
Implement bitwise numeric OR, AND, XOR, inversion, bit shifts

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#474] opened 2019-04-21 08:29 UTC
from #400 

- [ ] `~` (bitwise inversion);
- [ ] `|` (bitwise OR for Numeric);
- [ ] `&` (bitwise AND for Numeric);
- [ ] `^` (bitwise XOR for Numeric);
- [ ] `<<`, `>>`, `>>>` (bit shifts for Numeric);

**Comment by kushti** [comment] 2024-06-10 16:58
duplicate of #1006

**Closed by kushti** 2024-06-10 16:58 UTC
Labels: soft-fork
